[[language]]
name = "python"
language-servers = ["pyright"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "yaml"
scope = "source.yaml"
file-types = ["yaml", "yml"]
comment-token = "#"
language-servers = [ "yaml-language-server" ]

[language-server.yaml-language-server]
command = "yaml-language-server"
args = ["--stdio"]
