theme = "kanagawa"

[editor]
rulers = [80]
line-number = "relative"
bufferline = "always"
completion-timeout = 50
end-of-line-diagnostics = "hint"
true-color = true
completion-replace = true
popup-border = "all"

[editor.lsp]
# auto-signature-help = false
display-messages = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ["file-name"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = false
character = "│"

[keys.normal]
esc = ["collapse_selection","keep_primary_selection"]
C-y = [
  ':sh rm -f /tmp/zide-helix-yazi-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/zide-helix-yazi-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/zide-helix-yazi-file}',
  ':redraw',
]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
A-w = ":buffer-close"
A-s = ":wa"
A-l = ":lsp-restart"
A-r = ":config-reload"
